services:

    ### App (php, nodejs, python) (ports: php-fpm 9000, octane 8000, vite 5173)
    woochat-app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                TZ: ${WORKSPACE_TIMEZONE}
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: woochat-app
        hostname: woochat-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        ports:
            - "${APP_VITE_PORT:-5173}:5173"
        depends_on:
            - woochat-mariadb
            - woochat-redis
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        volumes:
            - ./:/var/www
            - ./docker/app/php_additional.ini:/usr/local/etc/php/conf.d/additional.ini
            - ./docker/app/.zshrc:/home/www-data/.zshrc
            - ./docker/app/bin:/home/www-data/bin
            - ~/.ssh:/home/www-data/.ssh:ro
            - ~/.gitconfig:/home/www-data/.gitconfig
        networks:
            - woochat-network

    ### Nginx (ports: nginx 80)
    woochat-nginx:
        image: nginx:stable-alpine
        container_name: woochat-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT:-80}:80"
        depends_on:
            - woochat-app
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/log:/var/log/nginx
        networks:
            - woochat-network

    ### MariaDB (ports: mysql 3306)
    woochat-mariadb:
        image: mariadb:10.11-rc
        container_name: woochat-mariadb
        restart: unless-stopped
        tty: true
        ports:
            - "${MYSQL_PORT}:3306" # Отключен внешний доступ
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - woochat-mariadb-data:/var/lib/mysql
            - ./docker/mariadb/sql:/docker-entrypoint-initdb.d
        networks:
            - woochat-network

    ### Redis (ports: redis 6379)
    woochat-redis:
        image: redis:alpine3.18
        container_name: woochat-redis
        restart: unless-stopped
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        volumes:
            - woochat-redis-data:/data
            - ./docker/redis/log:/log
        command: ["redis-server"]
        networks:
            - woochat-network

    ### phpMyAdmin (ports: gui 80)
    woochat-phpmyadmin:
        image: phpmyadmin:5.2
        container_name: woochat-phpmyadmin
        restart: unless-stopped
        ports:
            - "${PHPMYADMIN_PORT:-8010}:80"
        environment:
            PMA_HOST: woochat-mariadb
            UPLOAD_LIMIT: 512M
        networks:
            - woochat-network

    ### Mailpit (ports: smtp 1025, gui 8025)
    woochat-mailpit:
        image: axllent/mailpit
        container_name: woochat-mailpit
        restart: unless-stopped
        volumes:
            - woochat-mailpit:/data
        ports:
            - "${MAILPIT_PORT:-8012}:8025"
        environment:
            MP_MAX_MESSAGES: 500
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - woochat-network

    ### NGROK (ports: 4040)
    woochat-ngrok:
        image: 'ngrok/ngrok:alpine'
        container_name: woochat-ngrok
        environment:
            NGROK_AUTHTOKEN: 2nF9iO86sVLv0L4ChYwipa65RSC_zHbVpD9g2CZAvcwrBrgo
        command: "http --domain=legally-fleet-hen.ngrok-free.app woochat-nginx:80"
        ports:
            - '4040:4040'
        networks:
            - woochat-network
        depends_on:
            - woochat-app

networks:

    woochat-network:
        driver: bridge

volumes:

    woochat-mariadb-data:
        driver: local

    woochat-redis-data:
        driver: local

    woochat-mailpit:
        driver: local