<?php

return [
    'channel' => [
        "id" => "eb2f1b4f-c1bd-4d47-9158-01842999cf65",
        "code" => "ru.woochat.api",
        "secret_key" => "55caecffcff0c5fa0008c722fd87f3679283efc0",
        "name" => "WooChat",
        "webhook_url" => "https://api.woochat.ru/amocrm/webhook",
        "enabled" => true,
        "contact_email" => "vahagn99ghukasyan@gmail.com, tech8alex@yandex.ru",
        "created_at" => 1722344556,
        "updated_at" => 1722344556,
        "widget_code" => "woo_chat",
        "supports_reply" => true,
        "write_first" => true,
        "webhook_url_v2" => "https://api.woochat.ru/amocrm/webhook",
        "time_window" => [
            "enabled" => false,
            "expires" => 0,
            "tags" => null,
            "need_template" => false,
        ],
        "bot" => [
            "id" => "2582b180-46ea-42f1-88b6-1a84b6f11d24",
            "name" => "WooChat",
            "is_bot" => true,
        ],
        "webhook_events" => [
            "messages",
        ],
        "supports_voice" => true,
        "test_mode" => false,
        "icon" => "https://st1.amocrm.ru/origins_icons/ru.woochat.api.svg?1722344576",
        "webhook_v2" => true,
        "time_window_support" => false,
        "need_display_template" => false,
        "time_window_enum" => 0,
        "saves_files" => false,
        "reactions_all" => true,
        "reactions_list" => "",
        "en_enabled" => false,
        "client_uuid" => "02b4822e-1b63-4f2f-a0c9-d178c9527444",
        'hook_api_version' => 'v2',
    ],
];